config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("diary.urls", namespace="diary")),
    path("users/", include("users.urls", namespace="users")),
]

diary/urls.py
from django.urls import path

from . import views

app_name = "diary"

urlpatterns = [
    path("", views.Diary.as_view(), name="diary"),
    path("notes", views.Notes.as_view(), name="notes"),
    path("notes/<int:pk>", views.DetailedNote.as_view(), name="note"),
    path("notes/create", views.CreateNote.as_view(), name="new_note"),
    path("notes/<int:pk>/update", views.UpdateNote.as_view(), name="update_note"),
    path("notes/<int:pk>/delete", views.DeleteNote.as_view(), name="delete_note"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(template_name="users/login.html", success_url="/"),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", views.UserCreate.as_view(), name="registration"),
]

diary/models.py
from django.db import models

from users.models import User


# Create your models here.
class Note(models.Model):
    title = models.CharField("Название", max_length=100, blank=True, null=True)
    note = models.TextField("Запись")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Запись"
        verbose_name_plural = "Записи"

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    username = models.CharField("Имя пользователя", max_length=20)
    email = models.EmailField(unique=True, verbose_name="Email")

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.email

diary/forms.py
from django import forms

from diary.models import Note


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ["title", "note"]

    def __init__(self, *args, **kwargs):
        super(NoteForm, self).__init__(*args, **kwargs)

        self.fields["title"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Заголовок"}
        )
        self.fields["note"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Начните писать"}
        )

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)

        self.fields["username"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Имя пользователя"}
        )
        self.fields["email"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Электронная почта"}
        )
        self.fields["password1"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Придумайте пароль"}
        )
        self.fields["password2"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Подтвердите пароль"}
        )

diary/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView, View)

from diary.forms import NoteForm
from diary.models import Note


# Create your views here.
class Diary(View):
    model = Note
    template_name = "diary/diary.html"

    def get(self, request):
        return render(request, "diary/diary.html")


class Notes(LoginRequiredMixin, ListView):
    model = Note
    template_name = "diary/notes.html"
    context_object_name = "notes"

    def get_queryset(self):
        text = self.request.GET.get("search", None)
        if text:
            return Note.objects.filter(
                Q(owner=self.request.user)
                & (Q(title__icontains=text) | Q(note__icontains=text))
            )
        return Note.objects.filter(owner=self.request.user)


class DetailedNote(LoginRequiredMixin, DetailView):
    model = Note
    template_name = "diary/note.html"
    context_object_name = "note"


class CreateNote(LoginRequiredMixin, CreateView):
    model = Note
    form_class = NoteForm
    template_name = "diary/note_form.html"
    success_url = reverse_lazy("diary:notes")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class UpdateNote(LoginRequiredMixin, UpdateView):
    model = Note
    form_class = NoteForm
    template_name = "diary/note_form.html"
    success_url = reverse_lazy("diary:notes")

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return self.form_class
        raise PermissionDenied


class DeleteNote(LoginRequiredMixin, DeleteView):
    model = Note
    template_name = "diary/delete_note.html"
    success_url = reverse_lazy("diary:notes")

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.owner != request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

users/views.py
from django.views.generic import CreateView

from users.forms import RegistrationForm

from .models import User


# Create your views here.
class UserCreate(CreateView):
    model = User
    form_class = RegistrationForm
    template_name = "users/registration.html"
    success_url = "/"

diary/templates/diary/base.html
<!doctype html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Personal diary</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"></head>
<body bgcolor="#FDF6E5">
    <header>
        <div class="row text-center" style="width: 100vw;">
            <h1>Personal diary</h1>
        </div>
        <nav class="navbar bg-dark border-bottom border-body">
            <form method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <div class="btn-group" role="group" aria-label="Basic outlined example">
                    <a type="button" class="btn btn-outline-light" href="/">Главная</a>
                    {% if user.is_authenticated %}
                    <a type="button" class="btn btn-outline-light" href="{% url 'diary:new_note' %}">Создать запись</a>
                    <button class="btn btn-outline-light" type="submit">Выйти</button>
                    {% endif %}
                </div>
            </form>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

diary/templates/diary/delete_note.html
{% extends 'diary/base.html' %}
{% block content %}
<form class="row" method="post" enctype="multipart/form-data" style="width: 90vw;">
    {% csrf_token %}
    <div class="row g-0">
        <div class="col-md-6">
            <div class="col-4" style="position: absolute; margin: 2em 32vw;">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ note.title }}</h4>
                    </div>
                    <div class="card-body">
                        <p class="list-unstyled mt-3 mb-4 text-start m-3">
                            {{ note.note }}
                        </p>
                        <button type="submit" class="btn btn-outline-danger">
                            Удалить
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

diary/templates/diary/diary.html
{% extends 'diary/base.html' %}
{% block content %}
    <div class="col-6" style="position: absolute; margin-left:38vw; margin-top:5vh;">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <form method="post" action="{% url 'users:logout' %}" style="display:flex;flex-direction: column;">
                    {% csrf_token %}
                    {% if user.is_authenticated %}
                    <a type="button" class="btn btn-outline-light" href="{% url 'diary:notes' %}">Мои записи</a>
                    <button class="btn btn-outline-light" type="submit">Выйти</button>
                    {% else %}
                    <a type="button" class="btn btn-outline-light" href="{% url 'users:registration' %}">Регистрация</a>
                    <a type="button" class="btn btn-outline-light" href="{% url 'users:login' %}">Войти</a>
                {% endif %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

diary/templates/diary/note.html
{% extends 'diary/base.html' %}
{% block content %}
<div class="row g-0">
    <div class="col-md-6">
        <div class="col-4" style="position: absolute; margin: 2em 32vw;">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    {% if note.title %}
                    <h4 class="my-0 font-weight-normal">{{ note.title }}</h4>
                    {% endif %}
                </div>
                <div class="card-body">
                    <p class="list-unstyled mt-3 mb-4 text-start m-3">
                        {{ note.note }}
                    </p>
                    <div class="btn-group">
                        <a class="btn btn-outline-light" href="{% url 'diary:update_note' note.pk %}" role="button">Изменить</a>
                        <a class="btn btn-outline-danger" href="{% url 'diary:delete_note' note.pk %}" role="button">Удалить</a>
                        <a class="btn btn-outline-light", href="{% url 'diary:notes' %}">К списку записей</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary/note_form.html
{% extends 'diary/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8" style="position: absolute; margin:5vh 10vw;">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body" style="display:flex;flex-direction: column;">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-outline-light">
                        Сохранить
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary/notes.html
{% extends 'diary/base.html' %}
{% block content %}
<div class="row text-center" style="width: 90vw; padding: 2%">
    <form class="d-flex" role="search" method="GET" action="{% url 'diary:notes' %}">
        <input class="form-control me-2" type="search" name="search" placeholder="Поиск" aria-label="Search">
        <button class="btn btn-outline-info" type="submit">Поиск</button>
    </form>    
        {% for note in notes %}
        <div class="card" style="width: 18rem; margin: 0.2em;">
            <div class="card-body">
                {% if note.title %}
                <h5 class="card-title">{{ note.title }}</h5>
                {% endif %}
                <p class="card-text">{{ note.note|truncatechars:100 }}</p>
                <a type="button" class="btn btn-outline-light" href="{% url 'diary:note' note.pk %}">Подробнее</a>
                <a type="button" class="btn btn-outline-danger" href="{% url 'diary:delete_note' note.pk %}">Удалить</a>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'diary/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8" style="position: absolute; margin-left:10vw; margin-top:5vh;">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body" style="display:flex;flex-direction: column;">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-outline-light">
                        Войти
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/registration.html
{% extends 'diary/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8" style="position: absolute; margin-left:10vw; margin-top:5vh;">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body" style="display:flex;flex-direction: column;">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-outline-light">
                        Зарегистрироваться
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}